In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [3]:
img = cv2.imread("./data/clean_gauge1.jpg", cv2.IMREAD_COLOR)
cv2.imshow("hi", img)
cv2.waitKey()

-1

In [7]:
dst = img.copy()
gray = cv2.cvtColor(dst, cv2.COLOR_BGR2GRAY)
circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, 1, 100, param1 = 250, param2 = 10, minRadius = 80, maxRadius = 120)
cv2.imshow("hi", gray)
cv2.waitKey()

print(circles)

for i in circles[0]:
    cv2.circle(dst, (i[0], i[1]), i[2], (255, 255, 255), 5)

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[240.5 261.5 119.4]
  [171.5 180.5 110.6]
  [373.5 220.5 119.4]
  [296.5 156.5 108.4]
  [291.5 380.5 108.4]
  [414.5 324.5 101.8]
  [163.5 336.5 106.2]
  [510.5 392.5 115. ]
  [206.5  82.5 106.2]
  [363.5 458.5 118.3]
  [392.5 118.5 102.9]
  [ 77.5 250.5 113.9]
  [518.5 513.5 100.1]
  [ 41.5 392.5 118.3]
  [204.5 448.5 118.3]
  [479.5  48.5  93.8]
  [384.5 577.5 108.4]
  [ 57.5  10.5 112.8]]]


error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type


: 